export const SECOND_IN_MILLISECONDS = 1000;
export const MINUTES_IN_SECONDS = 60;
export const MINUTES_IN_MILLISECOND =
	MINUTES_IN_SECONDS * SECOND_IN_MILLISECONDS;

export const HOUR_IN_MINUTES = 60;
export const HOUR_IN_SECONDS = HOUR_IN_MINUTES * MINUTES_IN_SECONDS;
export const HOUR_IN_MILLISECONDS = HOUR_IN_SECONDS * SECOND_IN_MILLISECONDS;

export const DAY_IN_HOUR = 24;
export const DAY_IN_MINUTES = DAY_IN_HOUR * HOUR_IN_MINUTES;
export const DAY_IN_SECONDS = DAY_IN_MINUTES * MINUTES_IN_SECONDS;
export const DAY_IN_MILLISECONDS = DAY_IN_SECONDS * SECOND_IN_MILLISECONDS;

export const MONTH_IN_DAYS = 30;
export const MONTH_IN_MILLISECONDS = MONTH_IN_DAYS * DAY_IN_MILLISECONDS;
